name: plantpal
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  google_generative_ai: ^0.4.0
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.4
  geolocator: ^12.0.0
  http: ^1.2.1
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  path: ^1.9.0 
  curved_navigation_bar: ^1.0.3
  permission_handler: ^11.3.1 # YENİ EKLENEN PAKET
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"